In [1]:
import DataHelper
import pandas as pd
import numpy as np

In [2]:
e = DataHelper.eclass_data()

In [3]:
e.get_intro_pre()

,anon_student_id,survey_id,duration,q01a,q01b,q27a,q27b,q03a,q03b,q22a,...,q04b,q14a,q14b,q29a,q29b,q07a,q07b,q31a,q31b,ResponseId
19,11542,00STAnSs9Sqb8sB,234.0,5.0,5.0,5.0,5.0,3.0,5.0,1.0,...,5.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,R_1I5iowCdb6VvSeo
20,11543,00STAnSs9Sqb8sB,688.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,R_1I5iowCdb6VvSeo
21,11544,00STAnSs9Sqb8sB,298.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,R_1I5iowCdb6VvSeo
22,11545,00STAnSs9Sqb8sB,1073.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,...,3.0,3.0,5.0,5.0,5.0,3.0,1.0,5.0,5.0,R_1I5iowCdb6VvSeo
23,11546,00STAnSs9Sqb8sB,427.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,...,5.0,3.0,5.0,5.0,5.0,1.0,5.0,5.0,5.0,R_1I5iowCdb6VvSeo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39500,3084,ezo65e90NlkpwRD,412.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,...,5.0,5.0,5.0,5.0,5.0,1.0,1.0,5.0,5.0,R_2Y3sqmCv6vHoNbZ
39501,3085,ezo65e90NlkpwRD,847.0,5.0,5.0,3.0,3.0,3.0,5.0,1.0,...,5.0,5.0,5.0,3.0,5.0,1.0,3.0,5.0,5.0,R_2Y3sqmCv6vHoNbZ
39502,3086,ezo65e90NlkpwRD,244.0,5.0,5.0,3.0,5.0,5.0,5.0,5.0,...,5.0,3.0,5.0,3.0,5.0,3.0,5.0,5.0,5.0,R_2Y3sqmCv6vHoNbZ
39503,3087,ezo65e90NlkpwRD,407.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,...,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,5.0,R_2Y3sqmCv6vHoNbZ
39504,3088,ezo65e90NlkpwRD,304.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,...,5.0,5.0,5.0,5.0,5.0,3.0,3.0,5.0,5.0,R_2Y3sqmCv6vHoNbZ

In [4]:
pd.concat([e.get_intro_pre().anon_student_id, e.get_intro_post().anon_student_id]).nunique()

36538

In [5]:
survey_summary = pd.DataFrame(
    {'Number of instances of the survey offered':    [
        e.first_year_id.nunique()
        , e.buffy_id.nunique()
    ]
     
     ,'Number of unique universities':[
         e.get_cis_intro().anon_university_id.nunique(), e.get_cis_buffy().anon_university_id.nunique()
     ]
     
     , 'Number unique students': [
         pd.concat([e.get_intro_pre().anon_student_id, e.get_intro_post().anon_student_id]).nunique()
         , pd.concat([e.get_buffy_pre().anon_student_id, e.get_buffy_post().anon_student_id]).nunique()
                                              ]
     
   , 'Number of unique instructors': [
       e.get_cis_intro().anon_instructor_id.nunique()
       , e.get_cis_buffy().anon_instructor_id.nunique()
   ]
   , 'Number of matched Pre/Post Responses': [
       e.get_intro_matched().anon_student_id.nunique()
       , e.get_buffy_matched().anon_student_id.nunique()
   ]
   
    }
    , index = ['Introductory Labs', 'BUFFY']
)
survey_summary.transpose()

                                           Introductory Labs  BUFFY
Number of instances of the survey offered                363    236
Number of unique universities                             88     70
Number unique students                                 36538   6164
Number of unique instructors                             123    103
Number of matched Pre/Post Responses                   17583   2944